# Generated by Django 5.1.7 on 2025-03-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='PC', max_length=30)),
                ('identificador', models.IntegerField(default=0)),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.red')),
            ],
        ),
    ]
